on:
  push:
    branches: master
  pull_request:
    branches:
      - master

name: pkgdown-and-test-coverage

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          options(repos = c(rspatial = 'https://r-spatial.r-universe.dev', CRAN = 'https://cloud.r-project.org'))
          install.packages(c("remotes", "rcmdcheck"))
          install.packages("classInt")
          install.packages("stars", repos = "https://r-spatial.r-universe.dev")
          #remotes::install_deps(dependencies = TRUE)
          remotes::install_deps(dependencies = TRUE, type = "binary")
          remotes::install_cran("tmap", dependencies = TRUE, type = "binary")
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
